# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - binary: domain_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
      - ""
checksum:
  name_template: "checksums-{{ .Env.GO_VERSION }}.txt"
snapshot:
  name_template: "{{ .Tag }}-{{ .Env.GO_VERSION }}-next"
archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}_{{ .Env.GO_VERSION }}"
  format_overrides:
    - goos: windows
      format: zip
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - goos: linux
    goarch: amd64
    binary: domain_exporter
    image: zifter/domain_exporter
    dockerfile: Dockerfile
    tag_templates:
      - "{{ .Tag }}-{{ .Env.GO_VERSION }}"
      - "v{{ .Major }}-{{ .Env.GO_VERSION }}"
      - latest
  - goos: linux
    goarch: arm
    goarm: ""
    binary: domain_exporter
    image: zifter/domain_exporter
    dockerfile: Dockerfile
    tag_templates:
      - "{{ .Tag }}-{{ .Env.GO_VERSION }}-arm"
      - "v{{ .Major }}-{{ .Env.GO_VERSION }}-arm"
      - latest-arm
  - goos: linux
    goarch: arm64
    goarm: ""
    binary: domain_exporter
    image: zifter/domain_exporter
    dockerfile: Dockerfile
    tag_templates:
      - "{{ .Tag }}-{{ .Env.GO_VERSION }}-arm64"
      - "v{{ .Major }}-{{ .Env.GO_VERSION }}-arm64"
      - latest-arm64
